[Keras Documentation]https://keras.io/
### First type is sequential 
#### For more complicated model, should be using functional API

In [24]:
from sklearn import datasets
from pprint import pprint
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
iris = datasets.load_iris()
x, y = iris.data, iris.target
pprint(x[:5])

train_x, test_x, train_y, test_y = train_test_split(x,y,
                test_size = 0.2, random_state = 0)


print 'Shape of training features: {}'.format(train_x.shape)

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])
Shape of training features: (120, 4)


In [39]:
from sklearn.model_selection import ShuffleSplit
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

clf = GradientBoostingClassifier(n_estimators= 100, max_depth=2)
clf.fit(train_x, train_y)
print accuracy_score(test_y, clf.predict(test_x))

1.0


array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0])

In [49]:
#Sequential
from keras.models import Sequential
from keras.layers import Dense, Activation

#set up the model
model = Sequential()
model.add(Dense(output_dim=5, input_dim=4))
model.add(Activation('relu'))
model.add(Dense(output_dim = 3, input_dim=5))
model.add(Activation('softmax'))

In [63]:
#configure its learning process with .compile()
model.compile(loss= 'categorical_crossentropy', 
              optimizer = 'sgd', metrics=['accuracy'])

matrix_train_y = pd.get_dummies(train_y).astype(int).values
matrix_test_y = pd.get_dummies(test_y).astype(int).values
model.fit(train_x, matrix_train_y, verbose=False, nb_epoch= 300)


In [64]:
print model.predict_classes(test_x)
print test_y

30/30 [==============================] - 0s
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]


## Squential Model
[Official Documentation](https://keras.io/getting-started/sequential-model-guide/)

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation

model = Sequential([
        Dense(output_dim = 10, input_dim = 30),
        Activation('relu'),
        Dense(10),
        Activation('softmax'),
    ])

In [ ]:
#merging two sequential models
from keras.layers import Merge

left_branch = Sequential()
left_branch.add(Dense(32, input_dim=784))

right_branch = Sequential()
right_branch.add(Dense(32, input_dim=784))

merged = Merge([left_branch, right_branch], mode='concat')

final_model = Sequential()
final_model.add(merged)
final_model.add(Dense(10, activation='softmax'))

## Input shape
### The following are equivalent
1. input_shape = (10, 64)
2. input_length = 10, input_dim = 64
3. batch_input_shape = (None, 10, 64)

## Functional API

In [4]:
from keras.models import Model
from keras.layers import Input, Dense

inputs = Input(shape=(784,))
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

model = Model(input=inputs, output=predictions)
model.compile(optimizer'rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(data, labels)

#make the test input into another tensor
X = Input(shape=(784,))
y = model(X)

SyntaxError: invalid syntax (<ipython-input-4-566af3711ebc>, line 10)

In [ ]:
from keras.layers import Input, Embedding, LSTM, Dense, merge
from kears.models import Model

main_input = Input(shape=(100,), dtype='int32', name='main_input')
x = Embedding(output_dim=512, input_dim=10000, input_length=100)(main_input)
lstm_out = LSTM(32)x

auxiliary_output = Dense(1, activation='sigmoid', name='aux_output')(lstm_out)

auxiliary_input = Input(shape=(5,),name='aux_input')
