In [4]:
#optional keyword arguments
function add(x; y=1)
    return x + y
end

println(add(1))
print(add(1, y=1))

2
2

In [7]:
#args
function add2(x...)
    println(x)
    return sum(x)
end

add2(1, 2, 3)


(1, 2, 3)


6

In [11]:
#kwargs as keyword parameter
function add3(;x...)
    println(x)
    return sum([a[2] for a in x])
end

add3(a=1, b=2, c=3)

Any[(:a, 1), (:b, 2), (:c, 3)]


6

In [18]:
#multiple dispatch
function add_md(x::Number, y::Number)
    return x +y
end

function add_md(x::AbstractString, y::AbstractString)
    return x * ":::::::" * y
end

function add_md(x::Bool, y::Bool)
    return x || y
end

println(add_md(1, 2))
println(add_md("a","b"))
print(add_md(true, false))

3
a:::::::b
true

In [20]:
#@which tell you which method is being used
@which add_md(1, 2)

add_md(x::Number, y::Number) in Main at In[18]:3

In [21]:
#timing
@time add_md(1, 2)

  0.000006 seconds (84 allocations: 6.436 KiB)


3

In [23]:
#conditional operators
a, b = 10, 15
z = a > b ? 1:0
z

0

In [24]:
#with short circuit evaluation
function root(n:: Int)
    n > 0 || error("n must be non-negative")
    n == 0 && return 0
    return sqrt(n)
end

root(10)

3.1622776601683795

In [25]:
#for loop 
for n = 1:2:10
    print(n)
end


13579

In [27]:
arr = [x^2 for x in 1:10]
for i = 1:length(arr)
    println("the $i-th element is $(arr[i])")
end

the 1-th element is 1
the 2-th element is 4
the 3-th element is 9
the 4-th element is 16
the 5-th element is 25
the 6-th element is 36
the 7-th element is 49
the 8-th element is 64
the 9-th element is 81
the 10-th element is 100


In [30]:
#or use emuerate
for (ix, val) in enumerate(arr)
    println("the $ix-th element is $val")
end


the 1-th element is 1
the 2-th element is 4
the 3-th element is 9
the 4-th element is 16
the 5-th element is 25
the 6-th element is 36
the 7-th element is 49
the 8-th element is 64
the 9-th element is 81
the 10-th element is 100


In [31]:
#try ---- catch ------finally --- end
a = []
try
    pop!(a)
catch ex
    println(typeof(ex))
end

ArgumentError


In [ ]:
#Tasks: like yield in python
function fib_producer(n)
    a, b = (0, 1)
    for i = 1:n
        produce(b)
        a, b = (b, a+b)
    end
end


In [1]:
matrix = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [2]:
#dimension
ndims(matrix)

2

In [4]:
#number of rows and cols
size(matrix, 1) #row
size(matrix, 2) #col

2

In [8]:
#identity matrix
println(eye(2))

#convert it to Int array
convert(Array{Int}, eye(2))

[1.0 0.0; 0.0 1.0]


2×2 Array{Int64,2}:
 1  0
 0  1

In [12]:
#Transpose
ma = [1 2; 3 4]
ma'

2×2 Array{Int64,2}:
 1  3
 2  4

In [15]:
ma * ma'

2×2 Array{Int64,2}:
  5  11
 11  25

In [18]:
#inverse of a matrix => ma * in(ma) is identity
ma * inv(ma)

2×2 Array{Float64,2}:
 1.0          0.0
 8.88178e-16  1.0

In [19]:
#concatenation
v = [1, 2, 3]
w = [2, 4, 6]
vcat(v, w)

6-element Array{Int64,1}:
 1
 2
 3
 2
 4
 6

In [20]:
hcat(v, w)

3×2 Array{Int64,2}:
 1  2
 2  4
 3  6

In [21]:
#even better
[v w]

3×2 Array{Int64,2}:
 1  2
 2  4
 3  6

In [22]:
[v; w]

6-element Array{Int64,1}:
 1
 2
 3
 2
 4
 6

In [23]:
#reshaping
reshape(1:12, 3, 4)

3×4 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [24]:
ones(2)

2-element Array{Float64,1}:
 1.0
 1.0

In [25]:
trues(2)

2-element BitArray{1}:
 true
 true

In [31]:
#performance tips
#if the max size of array is known
arr = [1, 2, 3]
sizehint!(arr, 5)

#or even use ImmutableArrays

3-element Array{Int64,1}:
 1
 2
 3

In [42]:
d1 = Dict("a" => 1.4,  "b" => 2)
push!(d1, "c" => 5)

Dict{String,Any} with 3 entries:
  "c" => 5
  "b" => 2
  "a" => 1.4

In [44]:
s = Set([1, 2, 3])

Set([2, 3, 1])

## Metaprogramming

In [45]:
#creating expression
:(2 + 3)

:(2 + 3)

In [47]:
#creating longer expression
t = quote
    a = 42
    b = a ^ 2
    a - b + b * 3
end

quote  # In[47], line 3:
    a = 42 # In[47], line 4:
    b = a ^ 2 # In[47], line 5:
    (a - b) + b * 3
end

In [49]:
dump(t)

Expr
  head: Symbol block
  args: Array{Any}((6,))
    1: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 3
        2: Symbol In[47]
      typ: Any
    2: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol a
        2: Int64 42
      typ: Any
    3: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 4
        2: Symbol In[47]
      typ: Any
    4: Expr
      head: Symbol =
      args: Array{Any}((2,))
        1: Symbol b
        2: Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Symbol ^
            2: Symbol a
            3: Int64 2
          typ: Any
      typ: Any
    5: Expr
      head: Symbol line
      args: Array{Any}((2,))
        1: Int64 5
        2: Symbol In[47]
      typ: Any
    6: Expr
      head: Symbol call
      args: Array{Any}((3,))
        1: Symbol +
        2: Expr
          head: Symbol call
          args: Array{Any}((3,))
            1: Symbol -
          